name: McSetsPlugin
version: '${project.version}'
main: com.mcsets.plugin.McSetsPlugin
api-version: '1.18'
description: Receives webhooks and executes Minecraft commands.
authors: [Trainboy15]

commands:
  mcsets:
    description: McSets plugin management commands.
    usage: /mcsets <reload|status>
    permission: mcsets.admin
  reload:
    description: Reloads the McSets webhook server configuration.
    usage: /reload
    permission: mcsets.admin

permissions:
  mcsets.admin:
    description: Allows management of the McSets webhook plugin.
    default: op
